#!/bin/sh
apt-get install zip -y
apt-get update -y
apt-get install apache2 -y
cd /var/www
apt-get install php5 -y
/etc/init.d/apache2 restart
apt-get install mysql-server -y
apt-get install libapache2-mod-auth-mysql -y
apt-get install php5-mysql -y
apt-get install phpmyadmin -y
echo "include /etc/phpmyadmin/apache.conf" | sudo tee -a /etc/apache2/apache2.conf
service apache2 restart
cd /var/www
wget 31.220.56.219/painel.tar
tar -xvf painel.tar
cd /var/www
chmod -R 777 painel.tar
rm /etc/localtime
ln -s /usr/share/zoneinfo/America/Sao_Paulo /etc/localtime
sudo dpkg-reconfigure tzdata
clear
echo -e "\033[1;31mPAINEL INSTALADO COM SUCESSO.\033[0m"
